### ISSUE TITLE
Getting odd error message

### ISSUE THREAD

**Issue by huasome** [maxchk/puppet-varnish#62]
```
Error: Failed to apply catalog: Could not find filebucket  specified in backup
```

Running with puppet 3.8.1 with future parser enabled. None of the other manifests that use concat have this issue. Any hints? I'm calling varnish::vcl with the following hiera values:

```
varnish::vcl::backends:
  nginx_backend:
    host: 'nginx.org'
    port: '80'
  default_backend:
    host: '127.0.0.1'
    port: '80'
varnish::vcl::directors:
  nginx_cluster:
    backends: [ 'nginx_backend' ]
  default_cluster:
    backends: [ 'default_backend' ]
varnish::vcl::selectors:
  nginx_cluster:
    condition: 'req.url ~ "^/nginx"'
  default_cluster:
    condition: 'true'
```
